### ISSUE TITLE
 javax.crypto.IllegalBlockSizeException

### ISSUE THREAD

**Issue by soumyadipmaity** [castlabs/dashencrypt#17] opened 2015-01-12 16:35 UTC
I've used this command 

#java -jar dash.fragmencrypter-1.2.8-exe.jar encrypt vid_rep_1.mp4 vid_rep_2.mp4 vid_rep_3.mp4 sou_rep_1.mp4 --secretKey 000102030405060708090a0b0c0d0e0f --uuid 0696f5b0-b612-11e3-a5e2-0800200c9a66 --outputdir XXXcom.castlabs.dash dash.fragmencrypter 1.2.8

And get the following output. Please suggest.

vid_rep_1.mp4[1]'s starttime after edits: 0.0
vid_rep_2.mp4[1]'s starttime after edits: 0.0
vid_rep_3.mp4[1]'s starttime after edits: 0.0
sou_rep_1.mp4[1]'s starttime after edits: -0.105375

Jan 12, 2015 10:00:22 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence createSingleTrackDashedMp4s
INFO: Creating model for vid_rep_1.mp4... 
Jan 12, 2015 10:00:25 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence createSingleTrackDashedMp4s
INFO: Creating model for vid_rep_3.mp4... 
Jan 12, 2015 10:00:28 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence createSingleTrackDashedMp4s
INFO: Creating model for vid_rep_2.mp4... 
Jan 12, 2015 10:00:31 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence createSingleTrackDashedMp4s
INFO: Creating model for sou_rep_1.mp4... 
Jan 12, 2015 10:00:33 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence writeFilesSingleSidx
INFO: Writing... 
Jan 12, 2015 10:00:36 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence writeFilesSingleSidx
INFO: Done.
Jan 12, 2015 10:00:36 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence writeFilesSingleSidx
INFO: Writing... 
Jan 12, 2015 10:00:40 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence writeFilesSingleSidx
INFO: Done.
Jan 12, 2015 10:00:40 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence writeFilesSingleSidx
INFO: Writing... 
Jan 12, 2015 10:00:46 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence writeFilesSingleSidx
INFO: Done.
Jan 12, 2015 10:00:46 p.m. com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence writeFilesSingleSidx
INFO: Writing... 
Exception in thread "main" java.lang.RuntimeException: javax.crypto.IllegalBlockSizeException: 5 trailing bytes
   at com.googlecode.mp4parser.boxes.cenc.CencEncryptingSampleList$EncryptedSampleImpl.writeTo(CencEncryptingSampleList.java:147)
   at com.googlecode.mp4parser.authoring.builder.FragmentedMp4Builder$1Mdat.getBox(FragmentedMp4Builder.java:223)
   at com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence.writeFilesSingleSidx(DashFileSetSequence.java:375)
   at com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence.writeFiles(DashFileSetSequence.java:247)
   at com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence.run(DashFileSetSequence.java:196)
   at com.castlabs.dash.dashfragmenter.cmdlines.DashFileSetEncrypt.run(DashFileSetEncrypt.java:139)
   at com.castlabs.dash.dashfragmenter.Main.main(Main.java:48)
Caused by: javax.crypto.IllegalBlockSizeException: 5 trailing bytes
   at gnu.javax.crypto.jce.cipher.CipherAdapter.engineDoFinal(libgcj.so.10)
   at javax.crypto.Cipher.doFinal(libgcj.so.10)
   at javax.crypto.Cipher.doFinal(libgcj.so.10)
   at com.googlecode.mp4parser.boxes.cenc.CencEncryptingSampleList$EncryptedSampleImpl.writeTo(CencEncryptingSampleList.java:142)
   ...6 more

**Comment by sannies** [comment] 2015-02-25 16:36
Sorry for not coming back to you earlier, I have no clue what the reason might be. If you still have the problem let's try to fix it. I'll leave the ticket open for another week, after that I'll just close it as unreproducable.

**Closed** 2015-05-19 07:34 UTC
